name: Update Caddy Version

on:
  schedule:
    - cron: '0 */12 * * *'  # Vérifie toutes les 12 heures
  workflow_dispatch:  # Permet le déclenchement manuel

jobs:
  check-update:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      updated: ${{ steps.update-dockerfile.outputs.updated }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest Caddy version
        id: get-version
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/caddyserver/caddy/releases | jq -r '[.[] | select(.prerelease == false)][0].tag_name')
          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT
          echo "Latest version: $LATEST_VERSION"

      - name: Update Dockerfile
        id: update-dockerfile
        run: |
          CURRENT_VERSION=$(grep "RUN xcaddy build" Dockerfile | cut -d' ' -f3)
          LATEST_VERSION="${{ steps.get-version.outputs.version }}"
          
          if [ "$CURRENT_VERSION" != "$LATEST_VERSION" ]; then
            echo "Updating Dockerfile from $CURRENT_VERSION to $LATEST_VERSION"
            sed -i "s/build $CURRENT_VERSION/build $LATEST_VERSION/" Dockerfile
            sed -i "s/CADDY_VERSION=$CURRENT_VERSION/CADDY_VERSION=$LATEST_VERSION/" Dockerfile
            echo "updated=true" >> $GITHUB_OUTPUT
          else
            echo "Version is already up to date"
            echo "updated=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.update-dockerfile.outputs.updated == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: update Caddy to ${{ steps.get-version.outputs.version }}"
          title: "Update Caddy to ${{ steps.get-version.outputs.version }}"
          body: |
            Automated update of Caddy version to ${{ steps.get-version.outputs.version }}
            
            This PR was automatically created by the Caddy version update workflow.
          branch: update-caddy-version
          delete-branch: true

  build-and-push:
    needs: check-update
    if: needs.check-update.outputs.updated == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: update-caddy-version

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.date.outputs.date }}
            type=raw,value=${{ needs.check-update.outputs.version }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
